name: Download Itch.io Files

on:
  schedule:
    - cron: '0 5 * * *'  # 12 AM EST (5 AM UTC)
  workflow_dispatch:  # Allows manual triggering

jobs:
  download_files:
    runs-on: ubuntu-latest  # Runner type

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests  # Install requests library

    - name: Download Itch.io Files
      run: |
        python - <<EOF
        import os
        print("API Key:", os.getenv("ITCH_API_KEY"))  # Debugging line
        print("Directory contents:")
        for f in os.listdir():
            print(f)
        EOF
      env:
        ITCH_API_KEY: ${{ secrets.ITCH_API_KEY }}  # Pass the secret API key securely
