jobs:
  download_files:
    runs-on: ubuntu-latest

    env:
      ITCH_API_KEY: ${{ secrets.ITCH_API_KEY }}  # Pass the secret API key securely

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Download Itch.io Files
      run: |
        python - <<EOF
        import os
        print("API Key:", os.getenv("ITCH_API_KEY"))  # Debugging line
        print("Directory contents:")
        for f in os.listdir():
            print(f)
        EOF
